name: Test
on:
- push
jobs:
  test:
    runs-on: [self-hosted, cuda]
    name: Test
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: NiftyPET/NIMPA
        ref: dev2
        path: NIMPA
    - run: pip install -U ./NIMPA .[dev]
